CREATE TABLE `USER` (
	`USER_ID` INT NOT NULL,
	`EMAIL` varchar(100) NOT NULL UNIQUE,
	`PASSWORD` varchar(100) NOT NULL,
	PRIMARY KEY (`USER_ID`)
);

CREATE TABLE `USER_PROFILE` (
	`USER_ID` INT NOT NULL,
	`NAME` varchar(50) NOT NULL,
	`SURNAME` varchar(50) NOT NULL,
	`DATE_OF_BIRTH` DATE,
	`LOCATION` varchar(50),
	`GENDER` varchar(50),
	`USER_PIC` varchar(255) NOT NULL,
	PRIMARY KEY (`USER_ID`)
);

CREATE TABLE `RELATIONSHIP` (
	`USER_ID_1` INT NOT NULL,
	`USER_ID_2` INT NOT NULL,
	`STATUS` INT NOT NULL,
	`ACTION_USER` INT NOT NULL
);

CREATE TABLE `ALBUM` (
	`ALBUM_ID` INT NOT NULL,
	`USER_ID` INT NOT NULL,
	`DESCRIPTION` varchar(200),
	PRIMARY KEY (`ALBUM_ID`)
);

CREATE TABLE `PHOTO` (
	`PHOTO_ID` INT NOT NULL,
	`ALBUM_ID` INT NOT NULL,
	`PATH` varchar(100) NOT NULL,
	`DESCRIPTION` varchar(200),
	`NUMBER_OF_LIKES` INT,
	PRIMARY KEY (`PHOTO_ID`)
);

CREATE TABLE `COMMENTS` (
	`COMMENT_ID` INT NOT NULL,
	`AUTHOR_ID` INT NOT NULL,
	`PHOTO_ID` INT NOT NULL,
	`COMMENT` varchar(2000) NOT NULL,
	PRIMARY KEY (`COMMENT_ID`)
);

ALTER TABLE `USER_PROFILE` ADD CONSTRAINT `USER_PROFILE_fk0` FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`);

ALTER TABLE `RELATIONSHIP` ADD CONSTRAINT `RELATIONSHIP_fk0` FOREIGN KEY (`USER_ID_1`) REFERENCES `USER_PROFILE`(`USER_ID`);

ALTER TABLE `RELATIONSHIP` ADD CONSTRAINT `RELATIONSHIP_fk1` FOREIGN KEY (`USER_ID_2`) REFERENCES `USER_PROFILE`(`USER_ID`);

ALTER TABLE `RELATIONSHIP` ADD CONSTRAINT `RELATIONSHIP_fk2` FOREIGN KEY (`ACTION_USER`) REFERENCES `USER_PROFILE`(`USER_ID`);

ALTER TABLE `ALBUM` ADD CONSTRAINT `ALBUM_fk0` FOREIGN KEY (`USER_ID`) REFERENCES `USER_PROFILE`(`USER_ID`);

ALTER TABLE `PHOTO` ADD CONSTRAINT `PHOTO_fk0` FOREIGN KEY (`ALBUM_ID`) REFERENCES `ALBUM`(`ALBUM_ID`);

ALTER TABLE `COMMENTS` ADD CONSTRAINT `COMMENTS_fk0` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `USER_PROFILE`(`USER_ID`);

ALTER TABLE `COMMENTS` ADD CONSTRAINT `COMMENTS_fk1` FOREIGN KEY (`PHOTO_ID`) REFERENCES `PHOTO`(`PHOTO_ID`);

